const MESSAGE_TYPES = {
  FETCH_HTML_DOCUMENT: "FETCH_HTML_DOCUMENT",
  FETCH_HTML_DOCUMENT_RESPONSE: "FETCH_HTML_DOCUMENT_RESPONSE",
  CANCELLED: "CANCELLED",
  ERROR: "ERROR",
  ABORT: "ABORT",
  ABORTED: "ABORTED"
};

export {MESSAGE_TYPES};