#!/bin/sh
scr_dir="$(cd "$(dirname "$0")" && pwd)"
use_dir="$($scr_dir/i2prouter getdir)"

PIDFILE="$use_dir/gracefule_helper.pid"

if [ -f $PIDFILE ]; then
  PID=$(cat $PIDFILE)
  ps -p $PID > /dev/null 2>&1
  if [ $? -eq 0 ]; then
    exit 1
  else
    echo $$ > $PIDFILE
    if [ $? -ne 0 ]; then
      exit 1
    fi
  fi
else
  echo $$ > $PIDFILE
  if [ $? -ne 0 ]; then
    exit 1
  fi
fi
rm_pid() {
	test ! -f $PIDFILE || rm $PIDFILE
}

until [ $($use_dir/i2prouter status > /dev/null ; echo $?) -eq 1 ]; do
	sleep 1
done

sleep 5

eval "$use_dir/i2prouter start > /dev/null"
sleep 15
if [ $($use_dir/i2prouter status > /dev/null ; echo $?) -eq 0 ]; then
    rm_pid
    exit 0
else
    eval "$use_dir/i2prouter start > /dev/null"
    rm_pid
    exit 0
fi
