#!/bin/sh
# if I2P="%INSTALL_PATH" then manually change to to full path of i2p install e.g. /home/user/i2p (no trailing /)
I2P="%INSTALL_PATH"
echo " ➤ Initiating ping of $@…"
java -jar "$I2P/lib/i2ptunnel.jar" -die -e "ownDest yes" -e "ping $@"
