#!/bin/sh
# if I2P="%INSTALL_PATH" then manually change to to full path of i2p install e.g. /home/user/i2p (no trailing /)
scr_dir="$(cd "$(dirname "$0")" && pwd)"
I2P="$($scr_dir/i2prouter getdir)"

if [ -f "$I2P/lib/i2p.jar" ]; then
	echo " ➤ Attempting ssleepget retrieval of $@…"
	java -cp "$I2P/lib/i2p.jar" net.i2p.util.SSLEepGet "$@"
else
	echo "File $I2P/lib/i2p.jar not found."
	exit 1
fi
