#!/usr/bin/env python3
"""Guarantee two things about the IzPack langpacks, for both IzPack versions:

  1. Every code a descriptor declares has a langpack the compiler can reach, so a
     language /configui offers never silently falls back to English.

  2. No reachable langpack renders "Made with IzPack".

The two versions need opposite techniques, and the difference is not cosmetic.

IzPack 5 resolves one CustomLangPack and merges it with LocaleDatabase.add(),
which is a TreeMap putAll and so overrides whatever the langpack held. One file is
therefore enough for every language at once, and the upstream packs can be left
alone. The resource name is the literal "CustomLangPack.xml": AbstractResources
.resolveName only strips a leading slash and does no locale suffixing, so a
per-language "CustomLangPack.xml_<iso3>" is never looked up and the miss is
swallowed as a FINE-level "No custom langpack available". That is why this is one
file and not one per language.

IzPack 4 has no such mechanism - the string CustomLangPack appears in no IzPack 4
jar at all, and InstallerFrame reads installer.madewith straight out of
LocaleDatabase. The only lever is classpath shadowing: patches.jar precedes
standalone-compiler.jar on the compiler classpath, so shipping our own copy of a
pack at bin/langpacks/installer/<code>.xml wins. That is why some codes under
4/patches are copies of upstream packs rather than translations of ours.

Either way the packs are copied with their declared encoding intact. Chinese is
GB2312 and Bengali and Czech are ISO-8859-2, so rewriting one of those as UTF-8
would leave a file that declares an encoding it no longer uses, which Java's
ResourceBundle honours in preference to the bytes.

Usage:
  gen-izpack-langpacks.py           stage, blank and report; write the <res> lines
  gen-izpack-langpacks.py --check   report what is missing; write nothing
"""

import os
import re
import sys
import zipfile

REPO = os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.dirname(os.path.abspath(__file__)))))
IZ4 = "installer/lib/izpack/4"
IZ5 = "installer/lib/izpack/5"
IZ4_DESCRIPTOR = IZ4 + "/install.xml"
IZ5_DESCRIPTOR = IZ5 + "/install5.xml"
IZ4_JAR = IZ4 + "/standalone-compiler.jar"
IZ5_JAR = IZ5 + "/izpack-5.2.7/lib/izpack-core-5.2.7.jar"
IZ4_PACKS = IZ4 + "/patches/bin/langpacks/installer"
IZ5_PACKS = IZ5 + "/patches/resources/installer"
IZ4_JAR_PREFIX = "bin/langpacks/installer/"
IZ5_JAR_PREFIX = "com/izforge/izpack/bin/langpacks/installer/"
CUSTOM_PACK = "installer/lib/izpack/resources/CustomLangPack.xml"

MADEWITH = "installer.madewith"
BLANK = '<str id="installer.madewith" txt=""/>'

# Upstream packs are wildly inconsistent about how a <str> tag is laid out, and each
# variation defeats a naive pattern:
#
#   <str id="a" txt="1"/>              no space before the slash (most packs)
#   <str id="a" txt="1" />             space before the slash (slk: every tag)
#   <str id="a"\n     txt="1"/>       wrapped, most often once the id is long
#
# nld wraps 76 of its tags. A pattern that assumes one shape silently skips the
# others, which is indistinguishable from "already blank" or "no such id" and so
# survives a --check with nothing left to report. \s matches a newline as well as a
# space, so one pattern covers all three.
TAG = r'<str\s+id="([^"]+)"\s+txt="([^"]*)"\s*/>'

# IzPack 4 ships several languages under a spelling no JVM reports, so a descriptor
# that declares the modern code finds no pack. The distribution's own pack is
# reused under the modern name. Chinese is taken from chn rather than twn: zh and
# zh_TW both resolve to zho, so one pack serves both, and simplified Chinese is
# the better base for the larger of the two.
IZ4_LEGACY = {"zho": "chn", "ces": "cze", "nld": "ned",
              "ron": "rom", "slk": "svk", "fas": "fa"}

# IzPack 5 spells several of the same languages the legacy way too. Only these three
# matter here: the codes this installer declares that IzPack 5 does not already ship
# under the modern name.
IZ5_LEGACY = {"zho": "chn", "fas": "fa", "ind": "idn"}

CUSTOM_TEMPLATE = '''<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>

<!--
  Generated by installer/lib/izpack/gen-izpack-langpacks.py. Do not hand-edit; run
  the tool instead.

  IzPack titles the etched border around the installer's log window with
  installer.madewith, and every langpack the distribution ships carries its own
  translation of it. This pack is merged over whichever langpack the user picks by
  LocaleDatabase.add, which is a TreeMap putAll, so an entry here wins for every
  language at once - hence one file rather than one per language.

  installer.reversetitle is the window title the uninstaller uses. None of our
  langpacks carries it, so it would otherwise fall back to the distribution's
  English wording in every language; stating it here makes that deliberate.
-->
<izpack:langpack version="5.0"
                 xmlns:izpack="http://izpack.org/schema/langpack"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://izpack.org/schema/langpack http://izpack.org/schema/5.0/izpack-langpack-5.0.xsd">

    <str id="installer.madewith" txt=""/>
    <str id="installer.reversetitle" txt="I2P+ Installation Wizard [$APP_VER]"/>
</izpack:langpack>
'''


def path(rel):
    return os.path.join(REPO, rel)


def declared(descriptor):
    """iso3 codes a descriptor declares, with commented-out entries stripped."""
    text = re.sub(r"<!--.*?-->", "", open(path(descriptor),
                                         encoding="iso-8859-1").read(), flags=re.S)
    return {m.group(1) for m in re.finditer(r'<langpack iso3="([a-z]+)"', text)}


def jar_packs(jar, prefix):
    """{iso3: (jar entry name, raw bytes)} for the packs a distribution ships."""
    out = {}
    with zipfile.ZipFile(path(jar)) as zf:
        for n in zf.namelist():
            if n.startswith(prefix) and n.endswith(".xml"):
                out[n[len(prefix):-len(".xml")]] = (n, zf.read(n))
    return out


def our_packs(directory):
    """{iso3: file path} for the packs we maintain."""
    d = path(directory)
    if not os.path.isdir(d):
        return {}
    return {n[:-len(".xml")]: os.path.join(d, n)
            for n in os.listdir(d) if n.endswith(".xml")}


def str_values(text):
    """{id: txt} for every entry, whatever way its tag is laid out."""
    return {m.group(1): m.group(2) for m in re.finditer(TAG, text)}


def encoding_of(raw):
    m = re.search(rb'encoding="([^"]+)"', raw[:400])
    return m.group(1).decode() if m else "UTF-8"


def blank_madewith(text):
    """Return text with installer.madewith emptied, or None if already empty.

    None covers both an empty value and no entry at all: an id the pack never
    mentions cannot render anything, so neither needs a file edited.
    """
    if not re.search(r'<str\s+id="%s"\s+txt="[^"]' % MADEWITH, text):
        return None
    return re.sub(r'<str(\s+id="%s")\s+txt="[^"]*"\s*/>' % MADEWITH,
                  r'<str\1 txt=""/>', text)


def write_pack(target, text, encoding):
    data = text.encode(encoding)
    with open(target, "wb") as fh:
        fh.write(data)


def fix_ours(directory, codes, check, problems, label):
    """Blank madewith in the packs we own. Returns the set left needing help."""
    unblanked = set()
    for code, target in sorted(our_packs(directory).items()):
        raw = open(target, "rb").read()
        enc = encoding_of(raw)
        fixed = blank_madewith(raw.decode(enc))
        if fixed is None:
            continue
        unblanked.add(code)
        if check:
            problems.append("%s: %s.xml still renders \"Made with IzPack\""
                            % (label, code))
        else:
            write_pack(target, fixed, enc)
            print("  blanked madewith in %s/%s.xml (%s)"
                  % (directory, code, enc), file=sys.stderr)
    return unblanked


def stage(version, descriptor, jar, jar_prefix, packs_dir, legacy, shadow, check,
          problems):
    """Every declared code must resolve to a pack that omits the branding.

    shadow says whether a pack the distribution already ships has to be copied into
    our tree under our own name, and that differs by version for a reason worth
    stating, because it is not a preference:

      IzPack 4 has no override mechanism at all - the name CustomLangPack appears in
        no IzPack 4 jar, and InstallerFrame reads installer.madewith straight out of
        LocaleDatabase. The only lever is classpath shadowing: patches.jar precedes
        standalone-compiler.jar, so our copy wins. Required, not merely tidy.

      IzPack 5 does have one, the global CustomLangPack, and it is verified to win by
        adding the merge to this repo's checks. But its compiler reads a langpack from
        its own jar in preference to anything staged in the working directory, so a
        copy there would be dead weight that reads as if it did something. Left out.
    """
    codes = declared(descriptor)
    shipped = jar_packs(jar, jar_prefix)
    ours = our_packs(packs_dir)
    unblanked = fix_ours(packs_dir, codes, check, problems, version)

    for code in sorted(codes):
        if code in ours and code not in unblanked:
            continue                              # ours and already blank
        if code in ours:
            target = ours[code]
            enc = encoding_of(open(target, "rb").read())
            if check:
                problems.append("%s: %s was blanked in this run; commit it"
                                % (version, code))
            continue
        source = shipped.get(code) or shipped.get(legacy.get(code, ""))
        if source is None:
            problems.append("%s: %s is declared but neither %s nor %s has a pack"
                            % (version, code, os.path.basename(jar), packs_dir))
            continue
        entry, raw = source
        if not shadow:
            # Reachable from the distribution's own jar. The packaging path copies it
            # in preference to anything we stage, so a copy here would never ship.
            if check and blank_madewith(raw.decode(encoding_of(raw))) is not None:
                pass  # branding present but overridden; see izpack5()
            continue
        enc = encoding_of(raw)
        target = os.path.join(path(packs_dir), code + ".xml")
        if check:
            if not os.path.exists(target):
                problems.append("%s: %s has no pack under %s and would come from "
                                "%s with the branding intact"
                                % (version, code, packs_dir, entry))
            continue
        os.makedirs(path(packs_dir), exist_ok=True)
        text = blank_madewith(raw.decode(enc))
        write_pack(target, text or raw.decode(enc), enc)
        print("  %s: staged %s.xml from %s (%s, madewith %s)"
              % (version, code, entry, enc,
                 "blanked" if text else "already blank"), file=sys.stderr)
    orphans(codes, packs_dir, check, problems, version)


def izpack4(check, problems):
    stage("izpack 4", IZ4_DESCRIPTOR, IZ4_JAR, IZ4_JAR_PREFIX, IZ4_PACKS,
          IZ4_LEGACY, True, check, problems)


def izpack5(check, problems):
    """Stage the packs blanked, and keep the one global override in step."""
    stage("izpack 5", IZ5_DESCRIPTOR, IZ5_JAR, IZ5_JAR_PREFIX, IZ5_PACKS,
          IZ5_LEGACY, False, check, problems)

    target = path(CUSTOM_PACK)
    if check:
        if not os.path.exists(target):
            problems.append("izpack 5: %s is missing, so the branded string would "
                            "still be reachable" % CUSTOM_PACK)
            return
        have = str_values(open(target, "rb").read().decode("utf-8"))
        if have.get(MADEWITH):
            problems.append("izpack 5: %s does not blank %s"
                            % (CUSTOM_PACK, MADEWITH))
        return
    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(CUSTOM_TEMPLATE)
    print('    <res id="CustomLangPack.xml" src="%s"/>' % CUSTOM_PACK)


def orphans(codes, directory, check, problems, label):
    """A pack nothing declares is dead weight and will drift out of date."""
    for code in sorted(set(our_packs(directory)) - codes):
        if check:
            problems.append("%s: %s/%s.xml is not declared by any descriptor"
                            % (label, directory, code))
        else:
            os.remove(os.path.join(path(directory), code + ".xml"))
            print("  removed undeclared %s/%s.xml" % (directory, code),
                  file=sys.stderr)


def main():
    check = "--check" in sys.argv[1:]
    unknown = [a for a in sys.argv[1:] if a != "--check"]
    if unknown:
        sys.exit("gen-izpack-langpacks: unknown option(s) %s" % " ".join(unknown))

    problems = []
    izpack4(check, problems)
    izpack5(check, problems)

    if check:
        if problems:
            print("langpack gaps:")
            for p in problems:
                print("  " + p)
            return 1
        print("every declared langpack is reachable and none renders the branding")
        return 0
    print("gen-izpack-langpacks: done", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())