sonar.host.url=http://localhost:11199
sonar.projectKey=net.i2p.router:i2pplus
sonar.projectName=i2pplus
sonar.projectVersion=2.8.0
sonar.sources=core/java/src,router/java/src,apps
sonar.java.binaries=/tmp/build-i2p/build
sonar.java.libraries=/tmp/build-i2p/build/*.jar
sonar.sourceEncoding=UTF-8
sonar.working.directory=/tmp/opencode/sonar-scanner-work
sonar.exclusions=**/junit/**/*,**/test/**/*,**/demo/**/*,**/tests/**/*
