#!/bin/bash
#
# This launches I2PSnark and jetty in a separate jvm.
# The file jetty-i2psnark.xml must be present in the current directory.
# I2PSnark will be accessible at http://127.0.0.1:8002/
#

# Raise the soft open files soft ulimit to this value, if able
OPEN_FILES_ULIMIT=2048

raiseopenfilesulimit() {
    OPEN_FILES_SOFT=`ulimit -S -n` 2> /dev/null || return
    if [ "$OPEN_FILES_SOFT" != "unlimited" ]
    then
        if [ "$OPEN_FILES_ULIMIT" -gt "$OPEN_FILES_SOFT" ]
        then
            OPEN_FILES_HARD=`ulimit -H -n` 2> /dev/null || return
            if [ "$OPEN_FILES_HARD" != "unlimited" ]
            then
                if [ "$OPEN_FILES_ULIMIT" -gt "$OPEN_FILES_HARD" ]
                then
                    OPEN_FILES_ULIMIT="$OPEN_FILES_HARD"
                fi
            fi
            if [ "$OPEN_FILES_ULIMIT" -gt "$OPEN_FILES_SOFT" ]
            then
                ulimit -S -n "$OPEN_FILES_ULIMIT" > /dev/null 2>&1
            fi
        fi
    fi
}

raiseopenfilesulimit

I2P="."
java -jar "$I2P/i2psnark.jar"

# Uncomment the following if I2PSnark doesn't automatically open in a browser on launch
# echo "Launching I2PSnark in default browser..."
#
# if [[ "$OSTYPE" == "linux-gnu"* ]] || [["$OSTYPE" == "bsd"*]]
# then
#     xdg-open http://127.0.0.1:8002
# elif [[ "$OSTYPE" == "darwin"* ]]
# then
#     open http://127.0.0.1:8002
# fi