plugins {
    id 'java-library'
    id 'war'
}

sourceSets {
    main {
        java {
            srcDir 'java'
        }
    }
}

dependencies {
    api project(':router')
    api project(':apps:jetty')
    api files('../../installer/lib/wrapper/all/wrapper.jar')
    api fileTree("../jetty/apache-tomcat-${tomcatVersion}")
    api fileTree("../jetty/jetty-distribution-${jettyVersion}")
}

war {
    archiveBaseName.set('jsonrpc')
    rootSpec.exclude('**/*.jar')
    webXml = file('web.xml')
    dependsOn ':apps:i2ptunnel:i2ptunnelJar'
}
