package org.rrd4j.core;

/**
 * Wrap a exception generated by the backend store
 *
 * @author Fabrice Bacchella
 * @since 3.4
 */
public class RrdBackendException extends RrdException {

    /**
     * RrdBackendException.
     *
     * @param message the detail message describing the backend failure
     */
    public RrdBackendException(String message) {
        super(message);
    }

    /**
     * RrdBackendException.
     *
     * @param message the detail message describing the backend failure
     * @param cause the underlying exception that triggered the failure
     */
    public RrdBackendException(String message, Throwable cause) {
        super(message, cause);
    }
}
